# Generated by Django 6.0.1 on 2026-01-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0004_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
